version: '3.3'

services:

  app:
    build: .
    container_name: app
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./:/go/src/app/

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    restart: "no"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password