basePath: /api/v1
definitions:
  requests.Task:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  responses.JWT:
    properties:
      access_token:
        type: string
      type:
        type: string
    type: object
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/google-oauth:
    get:
      operationId: sign-up-google-callback
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.JWT'
        "201":
          description: User created
        "400":
          description: ""
        "500":
          description: ""
      summary: Redirect to app's page with login
  /tasks:
    post:
      consumes:
      - application/json
      operationId: create-task
      parameters:
      - description: Task info
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/requests.Task'
      - description: Insert your jwt
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "201":
          description: Task created
        "400":
          description: ""
        "500":
          description: ""
      summary: Create a task
securityDefinitions:
  BearerAuth:
    type: basic
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
